/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FollowupsRouteImport } from './routes/followups'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as LeadsIdEditRouteImport } from './routes/leads.$id.edit'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowupsRoute = FollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const LeadsIdEditRoute = LeadsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => LeadsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/edit': typeof LeadsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/edit': typeof LeadsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/followups': typeof FollowupsRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/leads/$id': typeof LeadsIdRouteWithChildren
  '/leads/$id/edit': typeof LeadsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/followups'
    | '/leads'
    | '/login'
    | '/map'
    | '/leads/$id'
    | '/leads/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/followups'
    | '/leads'
    | '/login'
    | '/map'
    | '/leads/$id'
    | '/leads/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/followups'
    | '/leads'
    | '/login'
    | '/map'
    | '/leads/$id'
    | '/leads/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  FollowupsRoute: typeof FollowupsRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/followups': {
      id: '/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof FollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/leads/$id/edit': {
      id: '/leads/$id/edit'
      path: '/edit'
      fullPath: '/leads/$id/edit'
      preLoaderRoute: typeof LeadsIdEditRouteImport
      parentRoute: typeof LeadsIdRoute
    }
  }
}

interface LeadsIdRouteChildren {
  LeadsIdEditRoute: typeof LeadsIdEditRoute
}

const LeadsIdRouteChildren: LeadsIdRouteChildren = {
  LeadsIdEditRoute: LeadsIdEditRoute,
}

const LeadsIdRouteWithChildren =
  LeadsIdRoute._addFileChildren(LeadsIdRouteChildren)

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRouteWithChildren
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRouteWithChildren,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  FollowupsRoute: FollowupsRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
